// Language definitions and translations
const LANGUAGES = {
    'zh-CN': {
        name: '中文',
        ui: {
            title: '🏛️ 博物馆打卡',
            subtitle: '让孩子爱上博物馆之旅',
            ageLabel: '孩子年龄：',
            ageOptions: {
                '3-6': '3-6岁 (学龄前)',
                '7-12': '7-12岁 (小学)',
                '13-18': '13-18岁 (中学)'
            },
            museumListTitle: '全国主要博物馆清单',
            visitedStats: '已参观',
            modalTitleSuffix: '参观指南',
            tabParent: '家长准备',
            tabChild: '孩子任务',
            tabShare: '生成海报',
            parentChecklistTitle: '家长准备事项',
            childChecklistTitle: '孩子探索任务',
            generatePoster: '生成海报',
            downloadPoster: '下载海报',
            shareDescription: '生成一张精美的参观纪念海报，记录孩子的博物馆探索之旅！',
            posterFooter: '由 MuseumCheck 博物馆打卡应用生成',
            noTasksMessage: '还没有完成的任务，继续加油！',
            languageLabel: '语言 / Language:'
        }
    },
    'en-US': {
        name: 'English',
        ui: {
            title: '🏛️ Museum Check',
            subtitle: 'Making children fall in love with museum visits',
            ageLabel: 'Child Age:',
            ageOptions: {
                '3-6': '3-6 years (Preschool)',
                '7-12': '7-12 years (Elementary)',
                '13-18': '13-18 years (Middle/High School)'
            },
            museumListTitle: 'Major Museums Checklist',
            visitedStats: 'Visited',
            modalTitleSuffix: 'Visit Guide',
            tabParent: 'Parent Prep',
            tabChild: 'Child Tasks',
            tabShare: 'Create Poster',
            parentChecklistTitle: 'Parent Preparation',
            childChecklistTitle: 'Child Exploration Tasks',
            generatePoster: 'Generate Poster',
            downloadPoster: 'Download Poster',
            shareDescription: 'Create a beautiful commemorative poster to record your child\'s museum exploration journey!',
            posterFooter: 'Generated by MuseumCheck Museum App',
            noTasksMessage: 'No completed tasks yet, keep going!',
            languageLabel: '语言 / Language:'
        }
    }
};

// Museum data with checklists for different age groups
const MUSEUMS = [
    {
        id: 'forbidden-city',
        'zh-CN': {
            name: '故宫博物院',
            location: '北京',
            description: '世界上现存规模最大、保存最为完整的木质结构古建筑群',
            tags: ['历史', '建筑', '文物']
        },
        'en-US': {
            name: 'Forbidden City',
            location: 'Beijing',
            description: 'The world\'s largest and most complete wooden architectural complex',
            tags: ['History', 'Architecture', 'Artifacts']
        },
        checklists: {
            'zh-CN': {
                parent: {
                    '3-6': [
                        '提前下载故宫APP，预约参观时间',
                        '准备舒适的步行鞋，全程需要走很多路',
                        '带上小零食和水，中途可以补充体力',
                        '准备简单的故事：皇帝和皇后住在这里',
                        '指出红色的墙和金色的屋顶，让孩子观察颜色'
                    ],
                    '7-12': [
                        '提前了解明清两朝历史背景',
                        '下载故宫APP，使用语音导览功能',
                        '准备纸笔，让孩子记录有趣的发现',
                        '讲解古代皇帝的日常生活',
                        '介绍中国古代建筑的特色'
                    ],
                    '13-18': [
                        '深入研究明清政治制度',
                        '分析故宫建筑的风水学原理',
                        '讨论文物保护的重要性',
                        '了解故宫的现代化管理',
                        '探讨历史与现代的对话'
                    ]
                },
                child: {
                    '3-6': [
                        '数一数有多少个门',
                        '找到最大的那个院子',
                        '看看屋顶上有什么小动物',
                        '找一找门上的门神',
                        '看红色的墙有多高'
                    ],
                    '7-12': [
                        '找到三大殿：太和殿、中和殿、保和殿',
                        '数一数太和殿前有多少台阶',
                        '寻找屋顶上的神兽，了解它们的作用',
                        '在珍宝馆找到最喜欢的宝物',
                        '观察古代皇帝用过的物品'
                    ],
                    '13-18': [
                        '研究故宫的对称设计原理',
                        '了解不同朝代的文物特征',
                        '分析一件文物的历史价值',
                        '探索故宫数字化保护技术',
                        '思考古代工匠技艺的传承'
                    ]
                }
            },
            'en-US': {
                parent: {
                    '3-6': [
                        'Download the Forbidden City app and book visit time in advance',
                        'Prepare comfortable walking shoes, lots of walking required',
                        'Bring snacks and water for energy during the visit',
                        'Prepare simple stories: emperors and empresses lived here',
                        'Point out red walls and golden roofs, let children observe colors'
                    ],
                    '7-12': [
                        'Learn about Ming and Qing dynasty history background',
                        'Download the app and use audio guide features',
                        'Prepare paper and pen for children to record discoveries',
                        'Explain daily life of ancient emperors',
                        'Introduce features of Chinese ancient architecture'
                    ],
                    '13-18': [
                        'Research Ming and Qing political systems in depth',
                        'Analyze feng shui principles in Forbidden City architecture',
                        'Discuss importance of cultural heritage preservation',
                        'Understand modern management of the Forbidden City',
                        'Explore dialogue between history and modernity'
                    ]
                },
                child: {
                    '3-6': [
                        'Count how many gates there are',
                        'Find the biggest courtyard',
                        'See what little animals are on the roofs',
                        'Look for door gods on the gates',
                        'See how tall the red walls are'
                    ],
                    '7-12': [
                        'Find the three main halls: Supreme Harmony, Central Harmony, Preserved Harmony',
                        'Count how many steps are in front of the Hall of Supreme Harmony',
                        'Look for mythical beasts on roofs and learn their purpose',
                        'Find your favorite treasure in the Treasure Gallery',
                        'Observe items used by ancient emperors'
                    ],
                    '13-18': [
                        'Study the symmetrical design principles of the Forbidden City',
                        'Learn characteristics of artifacts from different dynasties',
                        'Analyze the historical value of one artifact',
                        'Explore digital preservation technologies used',
                        'Think about inheritance of ancient craftsmanship'
                    ]
                }
            }
        }
    },
    {
        id: 'national-museum',
        'zh-CN': {
            name: '中国国家博物馆',
            location: '北京',
            description: '综合性历史艺术博物馆，展示中华民族悠久文化历史',
            tags: ['历史', '文化', '艺术']
        },
        'en-US': {
            name: 'National Museum of China',
            location: 'Beijing',
            description: 'Comprehensive historical and artistic museum showcasing China\'s long cultural history',
            tags: ['History', 'Culture', 'Art']
        },
        checklists: {
            'zh-CN': {
                parent: {
                    '3-6': [
                        '选择适合幼儿的展厅，避免过于复杂的内容',
                        '重点参观古代中国展，有很多有趣的文物',
                        '准备简单易懂的历史小故事',
                        '带上画笔和纸，让孩子画下感兴趣的文物',
                        '利用互动展示设备吸引孩子注意力'
                    ],
                    '7-12': [
                        '提前规划参观路线，重点看几个展厅',
                        '准备中国历史timeline，帮助理解',
                        '鼓励孩子提问和思考',
                        '使用博物馆提供的教育活动',
                        '讲解文物背后的故事'
                    ],
                    '13-18': [
                        '深入了解中华文明发展脉络',
                        '准备一些思辨性问题供讨论',
                        '关注近现代史展览',
                        '鼓励学生从多角度分析历史',
                        '结合当代社会发展思考'
                    ]
                },
                child: {
                    '3-6': [
                        '找一找最古老的东西',
                        '看看古代人用的碗和杯子',
                        '找到最漂亮的颜色',
                        '数一数有多少个动物',
                        '看看古代的钱是什么样子'
                    ],
                    '7-12': [
                        '了解中国古代四大发明',
                        '寻找不同朝代的代表文物',
                        '观察古代人的生活用品',
                        '学习一个历史典故',
                        '了解古代科技成就'
                    ],
                    '13-18': [
                        '研究中华文明的连续性特征',
                        '分析文物反映的历史信息',
                        '思考历史与现实的联系',
                        '探讨文化传承的重要意义',
                        '了解考古学的基本知识'
                    ]
                }
            },
            'en-US': {
                parent: {
                    '3-6': [
                        'Choose age-appropriate galleries, avoid overly complex content',
                        'Focus on Ancient China exhibition with many interesting artifacts',
                        'Prepare simple, understandable historical stories',
                        'Bring crayons and paper for children to draw artifacts',
                        'Use interactive displays to attract children\'s attention'
                    ],
                    '7-12': [
                        'Plan visit route in advance, focus on key galleries',
                        'Prepare Chinese history timeline to aid understanding',
                        'Encourage children to ask questions and think',
                        'Use museum educational activities',
                        'Explain stories behind artifacts'
                    ],
                    '13-18': [
                        'Deeply understand the development of Chinese civilization',
                        'Prepare thoughtful questions for discussion',
                        'Focus on modern and contemporary history exhibitions',
                        'Encourage students to analyze history from multiple perspectives',
                        'Consider connections to contemporary social development'
                    ]
                },
                child: {
                    '3-6': [
                        'Find the oldest things',
                        'Look at ancient bowls and cups',
                        'Find the prettiest colors',
                        'Count how many animals you see',
                        'See what ancient money looked like'
                    ],
                    '7-12': [
                        'Learn about China\'s Four Great Inventions',
                        'Find representative artifacts from different dynasties',
                        'Observe daily life items of ancient people',
                        'Learn one historical story',
                        'Understand ancient technological achievements'
                    ],
                    '13-18': [
                        'Study the continuity characteristics of Chinese civilization',
                        'Analyze historical information reflected by artifacts',
                        'Think about connections between history and reality',
                        'Explore the importance of cultural inheritance',
                        'Learn basic knowledge of archaeology'
                    ]
                }
            }
        }
    }
];

class MuseumCheckApp {
    constructor() {
        this.currentLanguage = this.loadLanguage();
        this.currentAge = document.getElementById('ageGroup').value;
        this.visitedMuseums = this.loadVisitedMuseums();
        this.museumChecklists = this.loadMuseumChecklists();
        this.init();
    }

    // Load saved language preference
    loadLanguage() {
        const saved = localStorage.getItem('selectedLanguage');
        return saved || 'zh-CN';
    }

    // Save language preference
    saveLanguage() {
        localStorage.setItem('selectedLanguage', this.currentLanguage);
    }

    // Get translated text for current language
    getText(key) {
        const keys = key.split('.');
        let value = LANGUAGES[this.currentLanguage];
        for (const k of keys) {
            value = value?.[k];
        }
        return value || key;
    }

    // Get museum data for current language
    getMuseumData(museum) {
        // Handle new multilingual format
        if (museum[this.currentLanguage]) {
            return {
                id: museum.id,
                name: museum[this.currentLanguage].name,
                location: museum[this.currentLanguage].location,
                description: museum[this.currentLanguage].description,
                tags: museum[this.currentLanguage].tags,
                checklists: museum.checklists[this.currentLanguage] || museum.checklists['zh-CN']
            };
        }
        // Handle old format (fallback to Chinese)
        return {
            id: museum.id,
            name: museum.name,
            location: museum.location,
            description: museum.description,
            tags: museum.tags,
            checklists: museum.checklists
        };
    }

    // Google Analytics tracking helper
    trackEvent(eventName, parameters = {}) {
        if (typeof gtag !== 'undefined' && window.GA_MEASUREMENT_ID !== 'GA_MEASUREMENT_ID') {
            gtag('event', eventName, parameters);
        }
    }

    init() {
        this.setupEventListeners();
        this.updateUI();
        this.renderMuseums();
        this.updateStats();
    }

    // Update UI text based on current language
    updateUI() {
        // Update title and subtitle
        document.querySelector('h1').textContent = this.getText('ui.title');
        document.querySelector('.subtitle').textContent = this.getText('ui.subtitle');
        
        // Update language selector label (it's bilingual)
        const langLabel = document.querySelector('.selector-group label');
        langLabel.textContent = this.getText('ui.languageLabel');
        
        // Update age selector
        const ageLabel = document.querySelectorAll('.selector-group label')[1];
        ageLabel.textContent = this.getText('ui.ageLabel');
        const ageSelect = document.getElementById('ageGroup');
        const ageOptions = ageSelect.querySelectorAll('option');
        ageOptions[0].textContent = this.getText('ui.ageOptions.3-6');
        ageOptions[1].textContent = this.getText('ui.ageOptions.7-12');
        ageOptions[2].textContent = this.getText('ui.ageOptions.13-18');
        
        // Update museum list title
        document.querySelector('.museum-list h2').textContent = this.getText('ui.museumListTitle');
        
        // Update visited label
        document.getElementById('visitedLabel').textContent = this.getText('ui.visitedStats');
        
        // Update page language attribute
        document.documentElement.lang = this.currentLanguage;
        
        // Update page title
        const titleSuffix = this.currentLanguage === 'en-US' ? 'MuseumCheck' : 'MuseumCheck';
        document.title = `${this.getText('ui.title').replace('🏛️ ', '')} - ${titleSuffix}`;
    }

    setupEventListeners() {
        // Language selector
        const languageSelector = document.getElementById('languageSelector');
        languageSelector.value = this.currentLanguage;
        languageSelector.addEventListener('change', (e) => {
            const oldLanguage = this.currentLanguage;
            this.currentLanguage = e.target.value;
            this.saveLanguage();
            this.updateUI();
            this.renderMuseums();
            
            // Track language change
            this.trackEvent('language_changed', {
                'previous_language': oldLanguage,
                'new_language': this.currentLanguage
            });
        });

        // Age group selector
        document.getElementById('ageGroup').addEventListener('change', (e) => {
            const oldAge = this.currentAge;
            this.currentAge = e.target.value;
            this.renderMuseums();
            
            // Track age group change
            this.trackEvent('age_group_changed', {
                'previous_age': oldAge,
                'new_age': this.currentAge
            });
        });

        // Modal close
        document.querySelector('.close').addEventListener('click', () => {
            this.closeModal();
        });

        // Click outside modal to close
        document.getElementById('museumModal').addEventListener('click', (e) => {
            if (e.target.id === 'museumModal') {
                this.closeModal();
            }
        });
    }

    loadVisitedMuseums() {
        const saved = localStorage.getItem('visitedMuseums');
        return saved ? JSON.parse(saved) : [];
    }

    saveVisitedMuseums() {
        localStorage.setItem('visitedMuseums', JSON.stringify(this.visitedMuseums));
    }

    loadMuseumChecklists() {
        const saved = localStorage.getItem('museumChecklists');
        return saved ? JSON.parse(saved) : {};
    }

    saveMuseumChecklists() {
        localStorage.setItem('museumChecklists', JSON.stringify(this.museumChecklists));
    }

    renderMuseums() {
        const grid = document.getElementById('museumGrid');
        grid.innerHTML = '';

        MUSEUMS.forEach(museum => {
            const museumData = this.getMuseumData(museum);
            const isVisited = this.visitedMuseums.includes(museum.id);
            const card = document.createElement('div');
            card.className = `museum-card ${isVisited ? 'visited' : ''}`;
            card.innerHTML = `
                <div class="museum-header">
                    <input type="checkbox" class="visit-checkbox" ${isVisited ? 'checked' : ''} 
                           data-museum="${museum.id}">
                    <div class="museum-info">
                        <h3>${museumData.name}</h3>
                        <div class="museum-location">📍 ${museumData.location}</div>
                    </div>
                </div>
                <p class="museum-description">${museumData.description}</p>
                <div class="museum-tags">
                    ${museumData.tags.map(tag => `<span class="tag">${tag}</span>`).join('')}
                </div>
            `;

            // Add click event for the card (excluding checkbox)
            card.addEventListener('click', (e) => {
                if (!e.target.classList.contains('visit-checkbox')) {
                    this.openMuseumModal(museum);
                }
            });

            // Add checkbox event
            const checkbox = card.querySelector('.visit-checkbox');
            checkbox.addEventListener('change', (e) => {
                e.stopPropagation();
                this.toggleMuseumVisit(museum.id);
            });

            grid.appendChild(card);
        });

        this.updateStats();
    }

    toggleMuseumVisit(museumId) {
        const index = this.visitedMuseums.indexOf(museumId);
        const museum = MUSEUMS.find(m => m.id === museumId);
        const museumData = this.getMuseumData(museum);
        const isNowVisited = index === -1;
        
        if (index > -1) {
            this.visitedMuseums.splice(index, 1);
        } else {
            this.visitedMuseums.push(museumId);
        }
        this.saveVisitedMuseums();
        this.renderMuseums();
        
        // Track museum visit toggle
        this.trackEvent('museum_visit_toggled', {
            'museum_id': museumId,
            'museum_name': museumData.name,
            'museum_location': museumData.location,
            'visited': isNowVisited,
            'age_group': this.currentAge,
            'language': this.currentLanguage
        });
    }

    updateStats() {
        const visitedCount = this.visitedMuseums.length;
        const totalCount = MUSEUMS.length;
        const percentage = totalCount > 0 ? Math.round((visitedCount / totalCount) * 100) : 0;

        document.getElementById('visitedCount').textContent = visitedCount;
        document.getElementById('totalCount').textContent = totalCount;
        document.getElementById('visitedPercentage').textContent = percentage;
    }

    openMuseumModal(museum) {
        const modal = document.getElementById('museumModal');
        const title = document.getElementById('modalTitle');
        const content = document.getElementById('modalContent');
        
        const museumData = this.getMuseumData(museum);

        title.textContent = `${museumData.name} - ${this.getText('ui.modalTitleSuffix')}`;

        content.innerHTML = `
            <div class="checklist-tabs">
                <button class="tab-button active" data-target="parent">${this.getText('ui.tabParent')}</button>
                <button class="tab-button" data-target="child">${this.getText('ui.tabChild')}</button>
            </div>
            <div id="parentChecklist" class="checklist-content">
                <h3>${this.getText('ui.parentChecklistTitle')}</h3>
                ${this.renderChecklist(museum.id, 'parent', museumData.checklists.parent[this.currentAge])}
            </div>
            <div id="childChecklist" class="checklist-content" style="display: none;">
                <h3>${this.getText('ui.childChecklistTitle')}</h3>
                ${this.renderChecklist(museum.id, 'child', museumData.checklists.child[this.currentAge])}
            </div>
        `;

        // Setup tab switching
        const tabButtons = content.querySelectorAll('.tab-button');
        tabButtons.forEach(button => {
            button.addEventListener('click', () => {
                const target = button.dataset.target;
                
                // Update active tab
                tabButtons.forEach(btn => btn.classList.remove('active'));
                button.classList.add('active');
                
                // Show corresponding content
                document.getElementById('parentChecklist').style.display = target === 'parent' ? 'block' : 'none';
                document.getElementById('childChecklist').style.display = target === 'child' ? 'block' : 'none';
            });
        });

        modal.classList.remove('hidden');
        
        // Track modal open
        this.trackEvent('museum_modal_opened', {
            'museum_id': museum.id,
            'museum_name': museumData.name,
            'museum_location': museumData.location,
            'age_group': this.currentAge,
            'language': this.currentLanguage
        });
    }

    renderChecklist(museumId, type, items) {
        const checklistKey = `${museumId}-${type}-${this.currentAge}`;
        const completed = this.museumChecklists[checklistKey] || [];

        return items.map((item, index) => {
            const itemId = `${checklistKey}-${index}`;
            const isCompleted = completed.includes(index);
            
            return `
                <div class="checklist-item">
                    <input type="checkbox" id="${itemId}" ${isCompleted ? 'checked' : ''} 
                           onchange="app.toggleChecklistItem('${checklistKey}', ${index})">
                    <label for="${itemId}">${item}</label>
                </div>
            `;
        }).join('');
    }

    toggleChecklistItem(checklistKey, itemIndex) {
        if (!this.museumChecklists[checklistKey]) {
            this.museumChecklists[checklistKey] = [];
        }
        
        const completed = this.museumChecklists[checklistKey];
        const index = completed.indexOf(itemIndex);
        
        if (index > -1) {
            completed.splice(index, 1);
        } else {
            completed.push(itemIndex);
        }
        
        this.saveMuseumChecklists();
    }

    closeModal() {
        document.getElementById('museumModal').classList.add('hidden');
    }
}

// Initialize the app when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
    window.app = new MuseumCheckApp();
});